### ISSUE TITLE
Due to my tomfoolery, the footers are messed up again. 

### ISSUE THREAD

**Issue by alancastilleja** [alancastilleja/SiteProject#25]
Just realized that the footers that look fine on mobile are literally floating off the bottom of the page on desktop full screens. Not a good look. Trying to figure out how to make it not bad.

**Comment by mrodriguez3313** [comment]
Wait I think I accidentally fixed this?

**Comment by mrodriguez3313** [comment]
I merged stuff onto master by accident and I ran the code and the footer was working correctly when I saw it. I tbh forgot all that I did

**Comment by alancastilleja** [comment]
when i changed them, i put the bottom as auto instead of 0. It looks fine on the index page but some of the state pages looks pretty awful. ugh

**Comment by mrodriguez3313** [comment]
Oh I see what your talking about

**Comment by mrodriguez3313** [comment]
I have actually the same issue on my branch on National-Organizations-page. The footer overlaps the content on mobile view.

**Comment by alancastilleja** [comment]
sure go ahead

**Comment by mrodriguez3313** [comment]
???

**Comment by alancastilleja** [comment]
Oh did you already push it to master? I said that as in to go ahead and push so i could see it. Whoopsss

**Comment by mrodriguez3313** [comment]
oh no just track my branch so I don't have to put technically buggy code on master.... again lol

**Comment by alancastilleja** [comment]
It's okay. I fixed it. Just had to mess with the padding a bit. What was the solution you used?

**Comment by mrodriguez3313** [comment]
Imma eat right now but I think were trying to go for a footer that feels like our current, but has larger padding like how we did in this commit 7bf32327f7fe904163cdd4aae78e05a2387f7adc  . 
If you run `git stash` you can stash your changes that you've currently made so that you don't have to delete your work. and then run `git fetch origin` and then `git checkout 7bf32327f7fe904163cdd4aae78e05a2387f7adc` and then you should have the code at that state and you'll see what I mean. and then to get back to your current state. you do `git checkout -- .` to get rid of some dumb flask file changes it does when you run the app. and then `git checkout  <name of branch you were on>`. And then finally ` git stash pop` to bring back all your changes that you stashed.

**Comment by mrodriguez3313** [comment]
I ended up not actually fixing anything lol

**Comment by alancastilleja** [comment]
Lmao. its fine. I did some changes that fixed the problems.
